services:
  dyndns:
    build: ./config/dynamic-dns
    container_name: dyndns
    depends_on: 
      - web

  web:
    image: nginx
    container_name: web
    env_file:
      - .env
    volumes:
      - ./htdocs:/usr/share/nginx/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}