services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_chat
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - database
    networks:
      - mysql-network
      - proxy-network
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: database
    # volumes:
    #   - ./src:/var/www

  queue-worker:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: queue_chat
    working_dir: /var/www
    command: php artisan queue:work
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - mysql-network
      - proxy-network
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: database

  reverb-server:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: reverb_chat
    working_dir: /var/www
    command: php artisan reverb:start --debug
    restart: unless-stopped
    ports:
      - "6001:6001"
    depends_on:
      - app
    networks:
      - mysql-network
      - proxy-network
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: database

  nginx:
    image: nginx:alpine
    container_name: nginx_chat
    restart: unless-stopped
    ports:
      - "8090:80"
      - "4433:443"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - mysql-network
      - proxy-network

  database:
    image: mariadb:latest
    container_name: database_chat
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mysql-network

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin_chat
    restart: unless-stopped
    environment:
      PMA_HOST: database_chat
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - mysql-network
    depends_on:
      - database

volumes:
  db-data:

networks:
  mysql-network:
    driver: bridge
  proxy-network:
    external: true
