version: '3.8'

services:
  # Application Service (PHP application)
  app:
    container_name: blog
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    depends_on:
      - db

  # Database Service (MySQL)
  db:
    image: mysql:8.0.1
    container_name: mysql-container
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mysql-network

  # Web Server Service (Nginx)
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - "8080:80"
    networks:
      - mysql-network
    depends_on:
      - db

volumes:
  db-data:

networks:
  mysql-network:
    driver: bridge
