services:
  app:
    container_name: blog
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - mysql-network
    platform: linux/arm64

  db:
    image: mariadb:latest
    container_name: mysql-container
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mysql-network
    platform: linux/arm64

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/:/etc/nginx/certs/
    depends_on:
      - app
      - db
    networks:
      - mysql-network
    platform: linux/arm64

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - "8080:80"
    networks:
      - mysql-network
    depends_on:
      - db
    platform: linux/arm64

volumes:
  db-data:

networks:
  mysql-network:
    driver: bridge
