name: Build AsciiDoc PDF and HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install asciidoctor asciidoctor-pdf rouge
          sudo apt-get update
          sudo apt-get install -y qpdf

      - name: Build main PDF and HTML with cover
        run: |
          cd docs

          asciidoctor \
            -a toc=left \
            -a icons=font \
            -a source-highlighter=rouge \
            -o index.html \
            README.adoc

          asciidoctor-pdf \
            -a pdf-theme=pi-theme.yml \
            -a pdf-fontsdir=theme/fonts \
            -a pdf-themesdir=theme \
            -o base.pdf \
            README.adoc

          # Añadir contraportada
          qpdf base.pdf --pages . theme/back.pdf -- --preserve-unreferenced -- 2ASIR_B_BERTOS_GOMEZ_ADRIAN_PUMUKYCHAT.pdf

      - name: Build annex PDFs and HTML with cover and back cover
        run: |
          cd docs
          for dir in Anexo*; do
            anexo=$(echo $dir | cut -d'-' -f2)

            asciidoctor \
              -o ${dir}/index.html \
              ${dir}/README.adoc

            asciidoctor-pdf \
              -a pdf-theme=pi-theme.yml \
              -a pdf-themesdir=./${dir} \
              -a pdf-fontsdir=theme/fonts \
              -o temp.pdf \
              ${dir}/README.adoc

            qpdf temp.pdf --pages . theme/back.pdf -- --preserve-unreferenced -- 2ASIR_B_BERTOS_GOMEZ_ADRIAN_PUMUKYCHAT-Anexo${anexo}.pdf

            rm temp.pdf
          done

      - name: Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
          keep_files: true
          enable_jekyll: false
