name: Build AsciiDoc PDF

on:
  push:
    branches: [ main ]

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install asciidoctor-pdf
          gem install rouge
          sudo apt-get update
          sudo apt-get install -y qpdf

      - name: Build base PDF from AsciiDoc
        run: |
          cd docs
          asciidoctor-pdf \
            -a pdf-theme=pi-theme.yml \
            -a pdf-fontsdir=theme/fonts \
            -a pdf-themesdir=theme \
            -o base.pdf \
            proyecto-integrado.adoc

      - name: Merge with back.pdf
        run: |
          cd docs
          qpdf base.pdf --pages . theme/back.pdf -- --preserve-unreferenced -- ../2ASIR_B_BERTOS_GOMEZ_ADRIAN_PUMUKYCHAT.pdf

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: true
          destination_dir: .
          enable_jekyll: false
